default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  username: utkukaynar
  password: zx

development:
  <<: *default
  database: yuneka_development

test:
  <<: *default
  database: yuneka_test

production:
  <<: *default
  database: yuneka_production
  username: utkukaynar
  password: zx
